
name: CI/CD pipeline
on: 
  push:
    branches:
         - main

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 
              uses: actions/checkout@v3
            
            - name: Install backend dependencies
              working-directory: ./backend
              run: npm install
            
            - name: Run backend tests
              working-directory: ./backend
              run: npm test
            
            # - name: Install Vercel CLI
            #   working-directory: ./backend
            #   run: npm install --global vercel@latest
            #       vercel --prod --token=${{ secrets.VERCEL_TOKEN }} \
            #       --scope=${{ secrets.VERCEL_ORG_ID }} \
            #       --confirm
        


    frontend:
      runs-on: ubuntu-latest
      needs: backend

      steps:
        - name: Checkout 
          uses: actions/checkout@v3
      
        - name: Install frontend dependencies
          working-directory: ./frontend/mizzou-scheduler
          run: npm install
        
        - name: Run frontend tests
          working-directory: ./frontend/mizzou-scheduler
          run: npm test
        
        # - name: Build frontend
        #   working-directory: ./frontend/mizzou-scheduler
        #   run: npm run build

        # - name: Deploy to Vercel
        #   working-directory: ./frontend/mizzou-scheduler
        #   run: vercel --prod --token=${{secrets.VERCEL_TOKEN}}
        #   env:
        #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
