# name: Frontend CI pipeline
# on: push

# jobs:
#     branch_name:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Checkout code
#               uses: actions/checkout@v3

#             - name: Echo Branch Name
            #   run: echo 'The name of this branch is' 
#     deploy:
#         needs: branch_name
#         runs-on: ubuntu-latest
#         steps:
#             - name: Deploying to production
#               run: 'echo Deploying...'

name: CI/CD pipeline
on: push

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 
              uses: actions/checkout@v3
            
            # - name: Use Node.js ${{ matrix.node-version }}
            #   uses: actions/setup-node@v4
            #   with:
            #     node-version: ${{ matrix.node-version }}
            #     cache: 'npm'
            
            - name: Install backend dependencies
              working-directory: ./backend
              run: npm install
            
            - name: Run backend tests
              working-directory: ./backend
              run: npm test


    frontend:
      runs-on: ubuntu-latest
      needs: backend

      steps:
        - name: Checkout 
          uses: actions/checkout@v3
      
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: 'npm'
      
        - name: Install frontend dependencies
          working-directory: ./frontend
          run: npm install
        
        - name: Run frontend tests
          working-directory: ./frontend
          run: npm test
