name: Frontend CI pipeline
on: push

jobs:
    branch_name:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Echo Branch Name
              run: echo 'The name of this branch is' ${{github.ref_name}}
    deploy:
        needs: branch_name
        runs-on: ubuntu-latest
        steps:
            - name: Deploying to production
              run: 'echo Deploying...'
